# Generated by Django 4.2.5 on 2023-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_comment_like",
        ),
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("harassment", "Harassment"),
                    ("inappropriate content", "Inappropriate Content"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("user", "comment"), name="unique_like"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("user", "comment"), name="unique_report"
            ),
        ),
    ]
