# Generated by Django 4.2.5 on 2023-10-31 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "reviews",
            "0002_remove_like_unique_comment_like_alter_report_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="like",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="report",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
