version: '3.9'

services:
  backend: 
      build: 
        context: ./backend
        dockerfile: Dockerfile
        
      environment:
        - SECRET_KEY=9+#v9b0%w8((73&vrtfxm*rc8udr+1vv*z&@xz#z%&n(nnk2y4
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_HOST=db
        - REDIS_HOST=redis

      ports:
        - '8000:8000'

      volumes:
        - ./backend:/app/backend

      depends_on:
        - db
        - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      
    environment:
      - WATCHPACK_POLLING=true

    ports:
      - '3000:3000'

    volumes:
      - ./client:/app/frontend

    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    
    ports:
      - '5432:5432'
      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  redis: 
    image: redis:7.2.1-alpine   
    ports:
      - '6379:6379'