version: '3.9'

services:
  backend: 
      build: 
        context: ./backend
        dockerfile: Dockerfile
        
      environment:
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_HOST=db
        - MEMCACHED_HOST=memcached

      ports:
        - '8000:8000'

      volumes:
        - ./backend:/app/backend

      depends_on:
        - db
        - memcached
        - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./client:/app/frontend

    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    
    ports:
      - '5432:5432'

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  memcached: 
    image: memcached:1.6.21-alpine
    ports:
      - '11211:11211'

  redis: 
    image: redis:7.2.1-alpine   
    ports:
      - '6380:6379'