# Generated by Django 4.1.7 on 2023-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentlike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
