# Generated by Django 4.2.5 on 2023-10-29 18:53

from django.db import migrations
import modules.utility.custom_fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0003_remove_commentlike_comment_remove_commentlike_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=modules.utility.custom_fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=128,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
