# Generated by Django 4.2.5 on 2023-10-30 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="productimage",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
