# Generated by Django 4.2.5 on 2023-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                ],
                default="pending_payment",
                max_length=30,
            ),
        ),
    ]
