# Generated by Django 4.2.5 on 2023-10-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_payment"),
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_method",
            new_name="method",
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
            preserve_default=False,
        ),
    ]
