# Generated by Django 4.2.5 on 2023-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_rename_payment_method_payment_method_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_main_payment",
            field=models.BooleanField(default=False),
        ),
    ]
