# Generated by Django 4.2.5 on 2023-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="expire_at",
            field=models.DateTimeField(),
        ),
    ]
