# Generated by Django 4.2.5 on 2023-10-18 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_address_created_at_address_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="state",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
