# Generated by Django 4.2.5 on 2023-11-03 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_remove_city_state_remove_order_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
