# Generated by Django 4.2.5 on 2023-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_cartitem_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
